= Bienvenido al Starknet Book en Español
:navtitle: The Starknet Book (versión español)

====
IMPORTANTE: El Starknet Book es un libro en progreso creado por el aporte de la comunidad. Algunoas secciones pueden estar incompletas o estar bajo revisión y están marcadas con un 🚧 emoji. Agradecemos tus sugerencias, comentarios y contribución al contenido para hacer de este libro una guía confiable para todos.
====

El Starknet Book es una guía paso a paso diseñada para enseñarte lo esencial del desarrollo en Starknet. Es un esfuezo en comunidad y cada capitulo te guiará a traves del ecosistema de Starknet.

Aprende Cairo, es el lenguaje de programación clave para los contratos inteligentes en Starknet, es crucial. Es por eso que este libro trabaja de la mano con el Cairo Book, otro recursod de la comunidad, puedes acceder a su versión en español https://book.cairo-lang.org/es/[**aquí**]. 

En resumen, el dominio de Cairo se alcanza a traves del Cairo Book, meintras que el Starknet Book se enfoca en las caracteristicas especificas de starknet. Para un entendimiento comleto  recomendados explorar ambos recursos que aportarán gran beneficion a todo aspirante profundamente comprometido a dessarrollar en Starknet. Este libro te introducirá en las herramientas, arquitectura, configuración de cuentas, STARKs y otras aplicaciones especificas de Starknet. 

== Tabla de contenidos

[.chapter-titles]
|===
|Capítulo | Descripción

|1: Introducción a Starknet | Profundiza en los conceptos fundamentales de Starknet y familiarízate con el despliegue de contratos inteligentes.

|2: Herramientas de Starknet | Familiarízate con las herramientas esenciales como Protostar y Hardhat, y explora cómo se pueden utilizar lenguajes como Javascript, Python y Rust para interactuar con Starknet.

|3: Arquitectura de Starknet | Descubre la estructura central de Starknet, obteniendo información sobre el ciclo de vida de las transacciones y la interacción entre el Secuenciador, el Validador y los Nodos.

|4: Abstracción de cuentas (Account Abstraction) | Profundiza en el enfoque único de Starknet para las cuentas de usuario, y domina el arte de crear cuentas personalizadas.

|5: Aplicaciones pioneras | Investiga la frontera de las capacidades de Starknet, incluyendo la Inteligencia Artificial On-Chain y Pruebas de Almacenamiento (Storage Proofs).

|6: STARKs | Sumérgete en las complejidades de los STARKs y su papel clave en el diseño de la visión de Starknet.
|===

== ¿Por donde empezar?

Dependiendo de tus metas e intereses, puedes elegir diversos caminos a traves del Starknet Book. Aqui les dejamos algunas recomendaciones basadas en varios objetivos:

* Si eres un *principiante* y quieres empezar a aprender sobre Cairo y Starknet desde cero, sigue el libro completo, empezando con la *Introdución a Starknet*.

* Si eres un *desarrolador experimentado* buscando sumergirte rapidamente en la la creación de contratos inteligentes escalables y descentralizados, enfocate en el el Cairo Book, particularmetne en el  ((https://book.cairo-lang.org/es/ch99-00-starknet-smart-contracts.html[*capítulo 12 Contratos Inteligentes en Starknet*])). 

* Si eres un *desarrollador fronted* queriendo integrar Starknet con frontend en Reac usando JavaScripts, dale prioridad a los subcapitulos de *starknet-js* y *starknet-react* en *Herramientas de Starknet*.

* Si eres del *DevOps* o un *operador de nodos* interesado en correr un nodo e indexador de starknet, ve directo a *Arquitectura de Starknet*.

* Si eres *analista de seguridad* o *auditor de contratos inteligentes* queriendo aprender sobre las caracteristicas de Abstracción de cuentas (Account Abstraction) y sus implicaciones, ve a *Abstracción de cuentas (Account Abstraction)*.

* Si eres un *entusiasta del blockchain* curioso acerca de los fundamentos en la arquitectura y mecanismos de Starknet y Cairo, explora *Arquitectura de Starknet*.

* Si eres un *experto criptografico* o *investigador* ansioso por comprender los fundamentos de de STARKs y sus implicaciones en el ecosistema de Starknet, adentrate en *STARKs*.

Siéntete libre de combinar estas rutas basado en tus intereses y requerimientos.

== Tu contribución es importante

Estamos encantados de que te unas a nosotros en este increible viaje para crear el mas completo recurso para el desarrollo en Starknet y Cairo. Al contribuir con el Starknet Book no solo estaras compartiendo tu conocimiento y experticia con el mundo, sino tambien estas contribuyendo a darle forma al futuro de las tecnologias descentralizadas. Juntos,  crearemos un curriculo exahustivo, atractivo y accesible que permitirá a los desarrolladores de todo el mundo aprovechar todo el potencial de Starknet.

Como contribuidor, seras parte de una comunidad creciente  y vibrante dedicada a traspasar los limites de lo que es posibel con la tecnologia descentralizada. Tendrás la oportunidad de colaborar con personas que comparten las mismas ideas alrededor del mundo, comparte tus ideas unicas y aprender de las de otros. Tu contribución no solo será enriquecedora para la comunidad de Starknet, sino que tambien dejatas un impacto duraredo en el campo de la tecnologia blockchain.

Entonces, ¿estas listo para embarcarte en esta epica aventura? Sumerjamonos y exploremos jungos el vasto y excitante mundo de Starknet. ¡Brindemos por los innumerables descubrimientos, avances e innovaciones que nos esperan!

Por favor consulta la https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[Guia de contribución] para instrucciones detalladas de como contribuir. Recuerda, cada contribuición,  no importa que tan pequeña sea, hace la diferencia.. Tus experiencia y pasion son invaluables en la creación de recursos verdaderametne excepcionales para la comunidad de Starknet. ¡Hasgamos historia juntos! 

Aquí hay algunas cosas que puedes hacer para ayuudar:

* En la mayoria de las secciones hay un mensaje para los colaboradores que quieren aportar contenido.
* ¿Secciónes vacias en un capítulo? Vamos por ello!
* ¿Consideras que el Starknet Book requiere de secciones adicionales? Proponlo.
* ¿Puede una sección ser mejorada? Sientete libre de modificarla.
* ¿Quieres agregar un lenguaje de programación adicionnal en los ejemplos? Por favor hazlo.
* Corrige los errores que encuentres.
* Por favor agrega explicacionnes en los comentarios de los ejercicios si consideras que los necesita.
* Añade ejercicios que muestren tu caracteristica favorita de Cairo..

== Recursos claves adicionales para el aprendizaje

Hemos recopilado una lista de valiosos recuerdos educativos que te ayudaran a profundizar tu entendimiento y mejorar tus habilidades con Cairo y mantenerte al tanto en el desarrollo de Starknet:

1. **Starklings**: Un recurso especificamente diseñado para guiarte a traves del aprendizaje en la programación con Cairo, asegurandote de alcanzar un nivel competente. Puedes acceder a el https://github.com/shramee/starklings-cairo1[aquí].
2. **Foros de la comunidad de Starknet**: Una plataforma en línea donde puede participar en debates sobre los últimos desarrollos en Starknet. Unete a la conversación https://community.starknet.io/[aquí].
3. **Documentación de Starknet**: Puedes navegar en la documentación https://docs.starknet.io/[aquí].
4. **Documentación de Cairo**: Explorala https://www.cairo-lang.org/docs[aquí].
5. **Starknet Developer Telegram (English)**: Una comunidad en ingles para los desarrolladores de Starknet. Esta es una gran plataforma para hacer conexiones, compartir ideas y resolver problemas juntos. Unete a la comunidad de Telegram en ingles  https://t.me/starknetna[aquí].
6. **Starknetes - Desarrollador@s de Starknet Telegram (Español)**: Comunidad enfocada en la enseñanza en español del ecosistema StarkNet. Unete a Telegram en español https://t.me/starknet_es[aquí]

== Autores del Starknet Book ✨

Extendemos nuestros mas sinceros agradecimientos a aquellos excepcionales individuos que han hecho contribuciones invaluables al Starknet Book:

[cols="5*"]
|===
a|
image::https://avatars.githubusercontent.com/u/16685321?v=4&s=100[width=100, link="https://github.com/drspacemn"]
Dr Spaceman +
a|
image::https://avatars.githubusercontent.com/u/113911244?v=4&s=100[width=100, link="https://github.com/JameStark"]
James Stark +
a|
image::https://avatars.githubusercontent.com/u/4755430?v=4&s=100[width=100, link="https://github.com/omarespejel"]
Omar Espejel +
a|
image::https://avatars.githubusercontent.com/u/27683905?v=4&s=100[width=100, link="https://github.com/gyan0890"]
Gyan +
a|
image::https://avatars.githubusercontent.com/u/22731646?v=4&s=100[width=100, link="https://github.com/l-henri"]
Henri +
a|
image::https://avatars.githubusercontent.com/u/2279046?v=4&s=100[width=100, link="https://github.com/barretodavid"]
David Barreto +
a|
image::https://avatars.githubusercontent.com/u/30735581?v=4&s=100[width=100, link="https://github.com/remedcu"]
Remedcu +
a|
image::https://avatars.githubusercontent.com/u/73983677?v=4&s=100[width=100, link="https://github.com/omahs"]
Omahs +
a|
image::https://avatars.githubusercontent.com/u/70894690?v=4&s=100[width=100, link="https://github.com/LucasLvy"]
Lucas @ Starkware +
a|
image::https://avatars.githubusercontent.com/u/33158502?v=4&s=100[width=100, link="https://github.com/qd-qd"]
Qd-Qd +
a|
image::https://avatars.githubusercontent.com/u/12909374?v=4&s=100[width=100, link="https://github.com/oboulant"]
Oboulant +
a|
image::https://avatars.githubusercontent.com/u/63842643?v=4&s=100[width=100, link="https://github.com/codeWhizperer"]
Code Whizperer +
a|
image::https://avatars.githubusercontent.com/u/2437994?v=4&s=100[width=100, link="https://github.com/avimak"]
Avi Mak +
a|
image::https://avatars.githubusercontent.com/u/36516516?v=4&s=100[width=100, link="https://github.com/robertkodra"]
Robert Kodra +
a|
image::https://avatars.githubusercontent.com/u/49245208?v=4&s=100[width=100, link="https://github.com/SupremeSingh"]
Manmit Singh +
a|
image::https://avatars.githubusercontent.com/u/85268534?v=4&s=100[width=100, link="https://github.com/LvisWang"]
Lvis Wang +
a|
image::https://avatars.githubusercontent.com/u/98833290?v=4&s=100[width=100, link="https://github.com/leablock"]
Leablock + 
a|
image::https://avatars.githubusercontent.com/u/113949669?v=4&s=100[width=100, link="https://github.com/cliraa"]
Carlos Lira + 
a|
image::https://avatars.githubusercontent.com/u/21693926?v=4&s=100[width=100, link="https://github.com/ArturVargas"]
Artur Vargas + 
a| 
image::https://avatars.githubusercontent.com/u/126797224?v=4&s=100[width=100, link="https://github.com/lorcan-codes"]
Lorcan-codes + 
a|
image::https://avatars.githubusercontent.com/u/117481421?v=4&s=100[width=100, link="https://github.com/devnet0x"]
Devnet0x +
a|
image::https://avatars.githubusercontent.com/u/2848732?v=4&s=100[width=100, link="https://github.com/ivpavici"]
Ivan Pavičić +
a|
image::https://avatars.githubusercontent.com/u/67330943?v=4&s=100[width=100, link="https://github.com/RaphaelNdonga"]
Raphael Ndonga + 
a|
image::https://avatars.githubusercontent.com/u/114395459?v=4&s=100[width=100, link="https://github.com/0xAsten"]
Asten +
a|
image::https://avatars.githubusercontent.com/u/35219743?v=4&s=100[width=100, link="https://github.com/trangnv"]
Trangnv +
a|
image::https://avatars.githubusercontent.com/u/102651969?v=4&s=100[width=100, link="https://github.com/0xKubitus"]
0xKubitus + 
a|
image::https://avatars.githubusercontent.com/u/12902455?v=4&s=100[width=100, link="https://github.com/EvolveArt"]
Evolve Art +
a|
image::https://avatars.githubusercontent.com/u/112663528?v=4&s=100[width=100, link="https://github.com/Nadai2010"]
Nadai +
a|
image::https://avatars.githubusercontent.com/u/30095502?v=4&s=100[width=100, link="https://github.com/prix0007"]
Prince Anuragi +
a|
image::https://avatars.githubusercontent.com/u/876976?v=4&s=100[width=100, link="https://github.com/ccolorado"]
Ccolorado +
a|
image::https://avatars.githubusercontent.com/u/95504156?v=4&s=100[width=100, link="https://github.com/die-h"]
Diego Hermida +
a|
image::https://avatars.githubusercontent.com/u/105909776?v=4&s=100[width=100, link="https://github.com/0x180db"]
0x180db +
a|
image::https://avatars.githubusercontent.com/u/11048263?v=4&s=100[width=100, link="https://github.com/shramee"]
Shramee Srivastav +
a|
image::https://avatars.githubusercontent.com/u/31094102?v=4&s=100[width=100, link="https://github.com/tranhoaison"]
Santala +
a|
image::https://avatars.githubusercontent.com/u/13951843?v=4&s=100[width=100, link="https://github.com/satyambnsal"]
Satyam Bansal +
a|
image::https://avatars.githubusercontent.com/u/25623039?v=4&s=100[width=100, link="https://github.com/zediogoviana"]
Zé Diogo + 
a|
image::https://avatars.githubusercontent.com/u/106890011?v=4&s=100[width=100, link="https://github.com/Pikkuherkko"]
Pikkuherkko +
a|
image::https://avatars.githubusercontent.com/u/2940022?v=4&s=100[width=100, link="https://github.com/DavideSilva"]
Davide Silva + 
a|
image::https://avatars.githubusercontent.com/u/22482966?v=4&s=100[width=100, link="https://github.com/leapalazzolo"]
Leapalazzolo +
a|
image::https://avatars.githubusercontent.com/u/65915812?v=4&s=100[width=100, link="https://github.com/keivinonline"]
Keivin +
a|
image::https://avatars.githubusercontent.com/u/87354252?v=4&s=100[width=100, link="https://github.com/lambda-0x"]
lambda-0x +
a|
image::https://avatars.githubusercontent.com/u/22297601?v=4&s=100[width=100, link="https://github.com/davelange"]
David Lange
a|
image::https://avatars.githubusercontent.com/u/46480795?v=4&s=100[width=100, link="https://github.com/0xlny"]
0xlenny 
a|
image::https://avatars.githubusercontent.com/u/125185051?v=4&s=100[width=100, link="https://github.com/LandauRaz"]
razlandau
a|
image::https://avatars.githubusercontent.com/u/24778804?v=4&s=100[width=100, link="https://github.com/neelkamath"]
neelkamath
a|
image::https://avatars.githubusercontent.com/u/75367288?v=4&s=100[width=100, link="https://github.com/Brivan-26"]
Mohamed Abdessamed
a|
image::https://avatars.githubusercontent.com/u/18651846?v=4&s=100[width=100, link="https://github.com/wenzhenxiang"]
xiang
a|
image::https://avatars.githubusercontent.com/u/39279277?v=4&s=100[width=100, link="https://github.com/stoobie"]
Steve Goodman
a|
image::https://avatars.githubusercontent.com/u/22782504?v=4&s=100[width=100, link="https://github.com/gianmarcoalarcon"]
GianMarco
a|
a|
|===
